name: "Testing Pull Request"

on:
  pull_request:
    branches:
      - "master"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.7, 3.8]
        
    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: anaconda, conda-forge
  
    - name: Install Python dependencies
      run: |
        conda create -y -n testenv python=${{ matrix.python-version }}
        conda init
        conda activate testenv        
        python -m pip install --upgrade pip
        python -m pip install smithers[vtk]
        python -m pip install .[test]

    - name: Test with pytest
      run: |
        python -m pytest
